adding commands summary script for quick reference
SD2E/sd2e-cli pull request #5
Opened 2018-02-02 14:38 UTC by wjallen

https://asciinema.org/a/KwOdCnqb6ogDofNppHA5hPnjq

2018-02-02 16:14 UTC, mwvaughn commented on bin/subcommands/commands
> +  abaco             Pring abaco command summaries
Print abaco command summaries

2018-02-02 16:15 UTC, mwvaughn requested changes
I approve, pending a fix to the "pring" typo in the abaco summary.

2018-02-02 18:02 UTC, wjallen commented
I fixed the typo

2018-02-06 14:53 UTC, johnfonner approved these changes
Could replace the long "elif" chain with a case statement, but it works.  Nice functionality addition.

2018-02-06 14:53 UTC, merged